# -*- coding: utf-8 -*-
"""MusicDB15

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_I9RUc462nNRzNCyzgOlZ3aw9858MPcu
"""

# -*- coding: utf-8 -*-
import pyodbc
import json
from flask import Flask, render_template_string, request, redirect, url_for, flash, jsonify

app = Flask(__name__)
app.secret_key = 'enterprise_super_secret_key_v11'

# ---------------------------------------------------------
# 資料庫連線設定
# ---------------------------------------------------------
DB_CONFIG = {
    'DRIVER': '{ODBC Driver 17 for SQL Server}',
    'SERVER': 'localhost',
    'DATABASE': 'MusicLibraryDB',
    'Trusted_Connection': 'yes'
}

def get_db_connection():
    try:
        conn_str = f"DRIVER={DB_CONFIG['DRIVER']};SERVER={DB_CONFIG['SERVER']};DATABASE={DB_CONFIG['DATABASE']};Trusted_Connection={DB_CONFIG['Trusted_Connection']}"
        conn = pyodbc.connect(conn_str)
        return conn
    except Exception as e:
        print(f"資料庫連線錯誤: {e}")
        return None

def get_next_id(cursor, table, pk_column):
    cursor.execute(f"SELECT MAX({pk_column}) FROM {table}")
    row = cursor.fetchone()
    return (row[0] or 0) + 1

# 初始化：確保 Songs 資料表有 play_count 欄位
def init_db_schema():
    conn = get_db_connection()
    if conn:
        cursor = conn.cursor()
        try:
            # 檢查是否存在 play_count 欄位，若無則建立
            cursor.execute("IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('Songs') AND name = 'play_count') BEGIN ALTER TABLE Songs ADD play_count INT DEFAULT 0; END")
            # 確保舊資料的 play_count 不是 NULL
            cursor.execute("UPDATE Songs SET play_count = 0 WHERE play_count IS NULL")
            conn.commit()
        except Exception as e:
            print(f"Schema 更新失敗: {e}")
        finally:
            conn.close()

# 啟動時初始化
init_db_schema()

# ---------------------------------------------------------
# 前端 HTML 模板 (強化對比度、動畫與排名顯示)
# ---------------------------------------------------------
BASE_TEMPLATE = """
<!DOCTYPE html>
<html lang="zh-TW">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MusicDB Enterprise | 智慧排名與點唱系統</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        :root {
            --primary: #2563eb;
            --dark: #0f172a;
            --ktv-bg: #0a0a0a;
            --ktv-accent: #ff0055;
            --ktv-text: #ffffff;
            --ktv-sub: #e2e8f0; /* 調亮灰色，確保清晰 */
            --mgr-sub: #475569; /* 調亮管理介面副標題 */
        }
        body { background-color: #f1f5f9; font-family: 'Segoe UI', 'Microsoft JhengHei', sans-serif; transition: 0.3s; }

        /* Sidebar */
        .sidebar { background: var(--dark); min-height: 100vh; color: white; position: fixed; width: 240px; z-index: 1000; }
        .sidebar .nav-link { color: #cbd5e1; padding: 12px 20px; border-radius: 8px; margin: 4px 15px; transition: 0.2s; }
        .sidebar .nav-link:hover, .sidebar .nav-link.active { background: var(--primary); color: white; box-shadow: 0 4px 10px rgba(37, 99, 235, 0.2); }
        .main-content { margin-left: 240px; padding: 40px; min-height: 100vh; }

        /* KTV Mode Special */
        .ktv-mode { background: var(--ktv-bg); color: var(--ktv-text); }
        .ktv-sidebar { background: #1a1a1a; border-radius: 20px; padding: 25px; border: 1px solid #333; position: sticky; top: 20px; }
        .ktv-song-card { background: #181818; border: 1px solid #222; border-radius: 15px; transition: 0.3s; margin-bottom: 20px; box-shadow: 0 10px 20px rgba(0,0,0,0.2); }
        .ktv-song-card:hover { border-color: var(--ktv-accent); transform: scale(1.02); box-shadow: 0 0 15px rgba(255, 0, 85, 0.4); }
        .btn-ktv-action { background: linear-gradient(45deg, #ff0055, #ff5500); border: none; color: white; border-radius: 50px; padding: 10px 35px; font-weight: bold; transition: 0.2s; }

        /* Dashboard Ranking Styles */
        .rank-gold { color: #fbbf24; }
        .rank-silver { color: #94a3b8; }
        .rank-bronze { color: #b45309; }
        .ranking-item { border-bottom: 1px solid #f1f5f9; padding: 12px 0; transition: 0.2s; }
        .ranking-item:last-child { border-bottom: none; }
        .ranking-item:hover { background-color: #f8fafc; }

        /* Typography */
        .text-subheader { color: var(--mgr-sub) !important; font-weight: 500; }
        .ktv-text-subheader { color: var(--ktv-sub) !important; font-weight: 400; }
        .card { border: none; border-radius: 18px; box-shadow: 0 5px 25px rgba(0,0,0,0.04); transition: 0.3s; }
        .stat-card-icon { width: 50px; height: 50px; border-radius: 15px; display: flex; align-items: center; justify-content: center; font-size: 1.5rem; }

        .ktv-cat-btn { border-radius: 10px; text-align: left; padding: 12px 15px; margin-bottom: 8px; transition: 0.2s; border: 1px solid #333; color: var(--ktv-sub); }
        .ktv-cat-btn.active { background: var(--ktv-accent) !important; color: white !important; border-color: var(--ktv-accent); }
    </style>
</head>
<body class="{{ 'ktv-mode' if active_page == 'ktv' else '' }}">
    {% if active_page != 'ktv' %}
    <div class="sidebar">
        <div class="p-4 text-center">
            <h4 class="fw-bold animate__animated animate__fadeIn"><i class="fas fa-record-vinyl text-info me-2 fa-spin"></i>MusicDB</h4>
            <small class="text-muted">Enterprise Console</small>
        </div>
        <nav class="nav flex-column">
            <a class="nav-link {{ 'active' if active_page == 'home' }}" href="/"><i class="fas fa-tachometer-alt me-2"></i>儀表板 Dashboard</a>
            <a class="nav-link {{ 'active' if active_page == 'add' }}" href="/add"><i class="fas fa-plus-circle me-2"></i>發行作品錄入</a>
            <a class="nav-link {{ 'active' if active_page == 'ml' }}" href="/ml"><i class="fas fa-brain me-2"></i>AI 智慧分析</a>
            <a class="nav-link {{ 'active' if active_page == 'ktv' }}" href="/ktv"><i class="fas fa-microphone-alt me-2 text-warning"></i>KTV 點歌模式</a>
            <a class="nav-link {{ 'active' if active_page == 'logs' }}" href="/logs"><i class="fas fa-history me-2"></i>回收站日誌</a>
        </nav>
    </div>
    {% endif %}

    <div class="{{ 'container-fluid py-5 px-lg-5' if active_page == 'ktv' else 'main-content' }}">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }} alert-dismissible fade show shadow border-0 animate__animated animate__slideInRight">
                        {{ message }} <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}

        __CONTENT_BLOCK__
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        function toggleInput(selectId, inputId) {
            const inputVal = document.getElementById(inputId).value;
            const selectEl = document.getElementById(selectId);
            if (inputVal && inputVal.trim() !== "") {
                selectEl.value = "";
                selectEl.disabled = true;
            } else {
                selectEl.disabled = false;
            }
        }
    </script>
</body>
</html>
"""

INDEX_HTML = """
<div class="row g-4 mb-5">
    <!-- 統計卡片 -->
    <div class="col-md-9">
        <div class="row g-4">
            <div class="col-md-4 animate__animated animate__fadeInDown">
                <div class="card p-4 border-start border-primary border-5">
                    <div class="d-flex justify-content-between">
                        <div><h6 class="text-subheader small text-uppercase mb-1">總發行曲目</h6><h2 class="fw-bold m-0">{{ stats.songs }}</h2></div>
                        <div class="stat-card-icon bg-primary text-white shadow"><i class="fas fa-music"></i></div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 animate__animated animate__fadeInDown" style="animation-delay: 0.1s;">
                <div class="card p-4 border-start border-success border-5">
                    <div class="d-flex justify-content-between">
                        <div><h6 class="text-subheader small text-uppercase mb-1">專輯總量</h6><h2 class="fw-bold m-0">{{ stats.albums }}</h2></div>
                        <div class="stat-card-icon bg-success text-white shadow"><i class="fas fa-compact-disc"></i></div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 animate__animated animate__fadeInDown" style="animation-delay: 0.2s;">
                <div class="card p-4 border-start border-warning border-5">
                    <div class="d-flex justify-content-between">
                        <div><h6 class="text-subheader small text-uppercase mb-1">創作者人數</h6><h2 class="fw-bold m-0">{{ stats.creators }}</h2></div>
                        <div class="stat-card-icon bg-warning text-white shadow"><i class="fas fa-users"></i></div>
                    </div>
                </div>
            </div>
            <div class="col-12 mt-4 animate__animated animate__fadeIn">
                <div class="card border-0 shadow-sm overflow-hidden">
                    <div class="card-header bg-white py-4 px-4 d-flex justify-content-between align-items-center border-0">
                        <div><h5 class="m-0 fw-bold">發行清單總覽</h5><p class="text-subheader small m-0">即時監控系統內所有已發行曲目</p></div>
                        <form action="/" method="GET" class="d-flex" style="width: 300px;">
                            <div class="input-group">
                                <input type="text" name="q" class="form-control rounded-start-pill border-0 bg-light px-4" placeholder="快速搜尋..." value="{{ q }}">
                                <button class="btn btn-primary rounded-end-pill px-3" type="submit"><i class="fas fa-search"></i></button>
                            </div>
                        </form>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-hover align-middle mb-0">
                            <thead class="table-light text-secondary small uppercase">
                                <tr><th class="ps-4">ID</th><th>標題</th><th>語言</th><th>點播數</th><th>製作群</th><th class="text-center">操作</th></tr>
                            </thead>
                            <tbody>
                                {% for song in songs %}
                                <tr>
                                    <td class="ps-4 text-muted small font-monospace">#{{ song.song_id }}</td>
                                    <td class="fw-bold text-dark">{{ song.song_title }}</td>
                                    <td><span class="badge bg-info-subtle text-info border border-info-subtle px-3">{{ song.song_language }}</span></td>
                                    <td class="text-primary fw-bold"><i class="fas fa-play-circle me-1"></i>{{ song.play_count }}</td>
                                    <td>
                                        {% if song.creators_split %}
                                            {% for c in song.creators_split %}<span class="badge bg-white text-dark border me-1">{{ c.name }} <small class="text-subheader">({{ c.role }})</small></span>{% endfor %}
                                        {% endif %}
                                    </td>
                                    <td class="text-center">
                                        <div class="btn-group">
                                            <a href="{{ url_for('edit_song', id=song.song_id) }}" class="btn btn-sm btn-outline-primary border-0"><i class="fas fa-edit"></i></a>
                                            <a href="/delete/{{ song.song_id }}" class="btn btn-sm btn-outline-danger border-0" onclick="return confirm('確定移除？');"><i class="fas fa-trash-alt"></i></a>
                                        </div>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- 點播排行榜 -->
    <div class="col-md-3 animate__animated animate__fadeInRight">
        <div class="card h-100 border-0 shadow-sm">
            <div class="card-header bg-white py-4 border-0">
                <h5 class="fw-bold m-0"><i class="fas fa-trophy text-warning me-2"></i>熱門點播排行榜</h5>
                <p class="text-subheader small m-0">根據 KTV 模式點播次數排名</p>
            </div>
            <div class="card-body pt-0">
                {% for song in top_songs %}
                <div class="ranking-item d-flex align-items-center">
                    <div class="me-3 fs-4 fw-bold {% if loop.index == 1 %}rank-gold{% elif loop.index == 2 %}rank-silver{% elif loop.index == 3 %}rank-bronze{% else %}text-light{% endif %}">
                        {{ loop.index }}
                    </div>
                    <div class="flex-grow-1 overflow-hidden">
                        <div class="fw-bold text-truncate text-dark">{{ song.song_title }}</div>
                        <div class="text-muted small text-truncate">發行語系：{{ song.song_language }}</div>
                    </div>
                    <div class="text-end ps-2">
                        <span class="badge bg-primary rounded-pill">{{ song.play_count }} 次</span>
                    </div>
                </div>
                {% endfor %}
                {% if not top_songs %}
                <div class="text-center py-5 text-muted fst-italic">目前尚無點播紀錄</div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
"""

ML_HTML = """
<div class="row g-4 mb-5">
    <div class="col-md-6 animate__animated animate__fadeInLeft">
        <div class="card h-100 p-4 border-0 shadow">
            <h5 class="fw-bold mb-4"><i class="fas fa-chart-pie me-2 text-primary"></i>創作者人才分佈 (K-Means 分析)</h5>
            <div style="height: 350px;"><canvas id="personaChart"></canvas></div>
        </div>
    </div>
    <div class="col-md-6 animate__animated animate__fadeInRight">
        <div class="card h-100 p-4 border-0 shadow">
            <h5 class="fw-bold mb-4"><i class="fas fa-info-circle me-2 text-info"></i>分析標籤定義與意義</h5>
            <div class="mb-4">
                <div class="p-3 mb-3 rounded-4 bg-primary bg-opacity-10 border-start border-primary border-5">
                    <h6 class="fw-bold text-primary"><i class="fas fa-microphone me-2"></i>純粹歌者 (Pure Vocalist)</h6>
                    <p class="small text-subheader m-0">主要負責音樂的作品呈現與「演唱」。在系統紀錄中，絕大多數身分為「歌手」，是品牌的第一線門面。</p>
                </div>
                <div class="p-3 mb-3 rounded-4 bg-secondary bg-opacity-10 border-start border-secondary border-5">
                    <h6 class="fw-bold text-secondary"><i class="fas fa-pen-nib me-2"></i>幕後創作人 (Behind-the-Scenes)</h6>
                    <p class="small text-subheader m-0">專注於詞曲研發。身分以「作詞」或「作曲」為主，是音樂內容產出的核心推手。</p>
                </div>
                <div class="p-3 rounded-4 bg-warning bg-opacity-10 border-start border-warning border-5">
                    <h6 class="fw-bold text-dark"><i class="fas fa-star me-2"></i>全能創作歌手 (All-rounder)</h6>
                    <p class="small text-subheader m-0">跨領域參與作品。在多個作品中同時兼任歌手與詞曲作者，具有極高的綜合商業開發價值。</p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="card p-0 border-0 shadow-sm overflow-hidden animate__animated animate__fadeIn">
    <table class="table table-hover align-middle mb-0">
        <thead class="bg-dark text-white"><tr><th class="ps-4">創作者姓名</th><th>歌手比</th><th>作曲比</th><th>作詞比</th><th>AI 智慧標籤</th></tr></thead>
        <tbody>
            {% for r in ml_results %}
            <tr>
                <td class="ps-4 fw-bold">{{ r.creator_name }}</td><td>{{ "%.0f"|format(r.singer_ratio*100) }}%</td><td>{{ "%.0f"|format(r.composer_ratio*100) }}%</td><td>{{ "%.0f"|format(r.lyricist_ratio*100) }}%</td>
                <td>
                    {% if r.cluster_id == 0 %}<span class="badge bg-primary px-3 rounded-pill shadow-sm"><i class="fas fa-microphone me-1"></i>{{ r.marketing_persona }}</span>
                    {% elif r.cluster_id == 1 %}<span class="badge bg-secondary px-3 rounded-pill shadow-sm"><i class="fas fa-pen-nib me-1"></i>{{ r.marketing_persona }}</span>
                    {% else %}<span class="badge bg-warning text-dark px-3 rounded-pill shadow-sm"><i class="fas fa-star me-1"></i>{{ r.marketing_persona }}</span>{% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    new Chart(document.getElementById('personaChart'), {
        type: 'doughnut',
        data: {
            labels: ['純粹歌者', '幕後創作人', '全能創作歌手'],
            datasets: [{
                data: [{{ persona_counts['vocalist'] }}, {{ persona_counts['bts'] }}, {{ persona_counts['allround'] }}],
                backgroundColor: ['#2563eb', '#64748b', '#f59e0b'],
                borderWidth: 0
            }]
        },
        options: { responsive: true, maintainAspectRatio: false }
    });
});
</script>
"""

KTV_HTML = """
<div class="d-flex justify-content-between align-items-center mb-5 animate__animated animate__fadeIn">
    <div><h2 class="m-0 fw-bold"><i class="fas fa-microphone-alt text-danger me-2 fa-pulse"></i>KTV 專業點唱系統</h2><p class="ktv-text-subheader small m-0">根據人氣排名，隨時點唱您的最愛</p></div>
    <div class="d-flex gap-4 align-items-center">
        <div class="position-relative" style="width: 450px;">
            <i class="fas fa-search position-absolute text-muted" style="left: 20px; top: 15px;"></i>
            <input type="text" id="ktvSearch" class="form-control bg-dark text-white border-secondary rounded-pill ps-5 py-2 shadow-lg" placeholder="搜尋歌名、歌手、詞曲人員..." onkeyup="searchKtv()">
        </div>
        <a href="/" class="btn btn-outline-light rounded-pill px-4 border-secondary"><i class="fas fa-arrow-left me-2"></i>返回後台</a>
    </div>
</div>

<div class="row g-4">
    <div class="col-md-3 animate__animated animate__fadeInLeft">
        <div class="ktv-sidebar">
            <h6 class="text-danger fw-bold mb-4 text-uppercase small" style="letter-spacing: 2px;">語言分類篩選</h6>
            <div class="d-grid gap-2">
                <button class="btn btn-outline-light ktv-cat-btn active" onclick="filterKtv('all', this)">全部曲目</button>
                <button class="btn btn-outline-light ktv-cat-btn" onclick="filterKtv('國語', this)">國語金曲</button>
                <button class="btn btn-outline-light ktv-cat-btn" onclick="filterKtv('粵語', this)">粵語經典</button>
                <button class="btn btn-outline-light ktv-cat-btn" onclick="filterKtv('英語', this)">西洋流行</button>
                <button class="btn btn-outline-light ktv-cat-btn" onclick="filterKtv('台語', this)">經典台語</button>
            </div>
            <hr class="my-4 border-secondary opacity-25">
            <h6 class="text-warning fw-bold mb-3 d-flex justify-content-between align-items-center">
                <span><i class="fas fa-list-ul me-2"></i>點播歷史 (session)</span>
                <span id="queue-count" class="badge bg-warning text-dark rounded-circle px-2 py-1">0</span>
            </h6>
            <div id="queue" class="ktv-text-subheader small italic" style="max-height: 350px; overflow-y: auto;">尚無點播紀錄</div>
        </div>
    </div>
    <div class="col-md-9 animate__animated animate__fadeIn">
        <div id="ktvList" class="row"></div>
    </div>
</div>

<script>
const songs = {{ songs_json | safe }};
let qCount = 0;

function render(data) {
    const list = document.getElementById('ktvList');
    if (data.length === 0) { list.innerHTML = '<div class="col-12 text-center py-5 opacity-50"><h4 class="ktv-text-subheader">查無相符歌曲</h4></div>'; return; }
    list.innerHTML = data.map(s => `
        <div class="col-md-6 mb-4 animate__animated animate__fadeInUp">
            <div class="ktv-song-card p-4 d-flex justify-content-between align-items-center h-100">
                <div>
                    <h5 class="fw-bold mb-2 text-white">${s.song_title}</h5>
                    <div class="ktv-text-subheader small mb-1"><i class="fas fa-users-cog me-1 text-info"></i>製作群：${s.all_creators}</div>
                    <div class="ktv-text-subheader small">
                        <span class="badge bg-dark border border-secondary text-secondary me-2">${s.song_language}</span>
                        <span class="text-warning"><i class="fas fa-fire me-1"></i>人氣：${s.play_count}</span>
                    </div>
                </div>
                <button class="btn btn-ktv-action flex-shrink-0" onclick="addQ(${s.song_id}, '${s.song_title}')">點歌</button>
            </div>
        </div>
    `).join('');
}

function searchKtv() {
    const q = document.getElementById('ktvSearch').value.toLowerCase();
    const filtered = songs.filter(s => s.song_title.toLowerCase().includes(q) || s.all_creators.toLowerCase().includes(q));
    render(filtered);
}

function filterKtv(lang, btn) {
    document.querySelectorAll('.ktv-cat-btn').forEach(b => b.classList.remove('active'));
    btn.classList.add('active');
    if(lang === 'all') render(songs); else render(songs.filter(s => s.song_language === lang));
}

function addQ(id, title) {
    // 1. 通知後端紀錄點播
    fetch('/api/play/' + id, { method: 'POST' })
    .then(r => r.json())
    .then(data => {
        if(data.status === 'success') {
            const qCont = document.getElementById('queue');
            const countBadge = document.getElementById('queue-count');
            if(qCont.innerText.includes('尚無點播')) qCont.innerHTML = '';

            qCount++;
            countBadge.innerText = qCount;

            const item = document.createElement('div');
            item.className = 'text-white py-3 border-bottom border-secondary d-flex justify-content-between animate__animated animate__fadeInLeft';
            item.innerHTML = `<span>🎤 ${title}</span> <small class="text-muted">已紀錄系統</small>`;
            qCont.prepend(item);
        }
    });
}
render(songs);
</script>
"""

EDIT_SONG_HTML = """
<div class="row justify-content-center">
    <div class="col-lg-8 animate__animated animate__fadeIn">
        <form method="POST" class="card p-5 border-0 shadow-lg">
            <h4 class="fw-bold mb-4 text-primary"><i class="fas fa-edit me-2"></i>編輯曲目內容</h4>
            <div class="mb-4"><label class="form-label fw-bold small text-subheader">作品名稱</label><input type="text" name="song_title" class="form-control form-control-lg" value="{{ song.song_title }}" required></div>
            <div class="row mb-4">
                <div class="col-md-6"><label class="form-label fw-bold small text-subheader">語言</label><select name="song_language" class="form-select">
                    {% for lang in ['國語', '英語', '粵語', '台語', '其他'] %}
                        <option value="{{ lang }}" {% if song.song_language == lang %}selected{% endif %}>{{ lang }}</option>
                    {% endfor %}
                </select></div>
                <div class="col-md-6">
                    <label class="form-label fw-bold small text-subheader">專輯/單曲設定</label>
                    <select name="al_sel" id="al_s" class="form-select mb-2">
                        <option value="">-- 單曲 --</option>
                        {% for a in albums %}<option value="{{ a.album_id }}" {% if song.album_id == a.album_id %}selected{% endif %}>{{ a.album_title }}</option>{% endfor %}
                    </select>
                    <input type="text" name="al_new" id="al_n" class="form-control" placeholder="或建立新專輯" oninput="toggleInput('al_s','al_n')">
                </div>
            </div>
            <div class="p-4 bg-light rounded-4 mb-4 border shadow-sm">
                <h6 class="fw-bold mb-3 border-bottom pb-2 text-dark">製作群詳情</h6>
                {% for role_label, role_name, sel_id, new_id in [('歌手','歌手','s_s','s_n'),('作曲','作曲','c_s','c_n'),('作詞','作詞','l_s','l_n')] %}
                <div class="row g-2 mb-3 align-items-center">
                    <div class="col-3 text-end fw-bold small text-secondary">{{ role_label }}:</div>
                    <div class="col-4"><select name="{{ sel_id }}" id="{{ sel_id }}" class="form-select form-select-sm">
                        <option value="">-- 選擇 --</option>
                        {% for c in creators %}
                            <option value="{{ c.creator_id }}" {% if current_roles[role_name] == c.creator_id %}selected{% endif %}>{{ c.creator_name }}</option>
                        {% endfor %}
                    </select></div>
                    <div class="col-5"><input type="text" name="{{ new_id }}" id="{{ new_id }}" class="form-control form-control-sm" placeholder="或手動輸入姓名" oninput="toggleInput('{{ sel_id }}','{{ new_id }}')"></div>
                </div>
                {% endfor %}
            </div>
            <div class="d-flex gap-3">
                <button type="submit" class="btn btn-primary py-3 fw-bold rounded-pill shadow-lg flex-grow-1">更新作品並重置點播</button>
                <a href="/" class="btn btn-outline-secondary py-3 fw-bold rounded-pill px-4">取消</a>
            </div>
        </form>
    </div>
</div>
"""

# ---------------------------------------------------------
# 路由邏輯
# ---------------------------------------------------------

@app.route('/')
def index():
    conn = get_db_connection()
    if not conn: return "DB 連線失敗"
    cursor = conn.cursor()
    q = request.args.get('q', '').strip()

    # 基本統計
    cursor.execute("SELECT COUNT(*) FROM Songs"); s_c = cursor.fetchone()[0]
    cursor.execute("SELECT COUNT(*) FROM Albums"); a_c = cursor.fetchone()[0]
    cursor.execute("SELECT COUNT(*) FROM Creators"); c_c = cursor.fetchone()[0]
    cursor.execute("SELECT COUNT(*) FROM Songs_Deleted_Log"); l_c = cursor.fetchone()[0]

    # 排行榜前五名
    cursor.execute("SELECT TOP 5 song_title, song_language, play_count FROM Songs ORDER BY play_count DESC, song_title ASC")
    top_songs = cursor.fetchall()

    sql = """
    SELECT s.song_id, s.song_title, s.song_language, s.play_count, a.album_title,
           STRING_AGG(ISNULL(c.creator_name,'') + ':' + ISNULL(scr.role,''), '|') as raw_c
    FROM Songs s
    LEFT JOIN Albums a ON s.album_id = a.album_id
    LEFT JOIN Song_Creator_Roles scr ON s.song_id = scr.song_id
    LEFT JOIN Creators c ON scr.creator_id = c.creator_id
    """
    if q:
        sql += " WHERE s.song_title LIKE ? OR c.creator_name LIKE ? OR a.album_title LIKE ?"
        cursor.execute(sql + " GROUP BY s.song_id, s.song_title, s.song_language, s.play_count, a.album_title ORDER BY s.song_id DESC", (f'%{q}%', f'%{q}%', f'%{q}%'))
    else:
        cursor.execute(sql + " GROUP BY s.song_id, s.song_title, s.song_language, s.play_count, a.album_title ORDER BY s.song_id DESC")

    rows = cursor.fetchall()
    songs = []
    for r in rows:
        c_list = []
        if r.raw_c:
            for item in r.raw_c.split('|'):
                p = item.split(':')
                if p[0]: c_list.append({'name': p[0], 'role': p[1]})
        songs.append({
            'song_id': r.song_id, 'song_title': r.song_title, 'song_language': r.song_language,
            'play_count': r.play_count or 0, 'album_title': r.album_title, 'creators_split': c_list
        })

    conn.close()
    return render_template_string(BASE_TEMPLATE.replace('__CONTENT_BLOCK__', INDEX_HTML), songs=songs, top_songs=top_songs, stats={'songs':s_c, 'albums':a_c, 'creators':c_c, 'logs':l_c}, q=q, active_page='home')

@app.route('/api/play/<int:id>', methods=['POST'])
def record_play(id):
    """API: 紀錄歌曲點播次數"""
    conn = get_db_connection()
    if conn:
        cursor = conn.cursor()
        try:
            cursor.execute("UPDATE Songs SET play_count = ISNULL(play_count, 0) + 1 WHERE song_id = ?", (id,))
            conn.commit()
            return jsonify({'status': 'success'})
        except:
            conn.rollback()
            return jsonify({'status': 'error'})
        finally:
            conn.close()
    return jsonify({'status': 'failed'})

@app.route('/ktv')
def ktv_mode():
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("""
        SELECT s.song_id, s.song_title, s.song_language, a.album_title, s.play_count,
               STRING_AGG(ISNULL(c.creator_name,'未知') + ' (' + ISNULL(scr.role,'') + ')', ', ') as all_creators
        FROM Songs s
        LEFT JOIN Albums a ON s.album_id = a.album_id
        LEFT JOIN Song_Creator_Roles scr ON s.song_id = scr.song_id
        LEFT JOIN Creators c ON scr.creator_id = c.creator_id
        GROUP BY s.song_id, s.song_title, s.song_language, a.album_title, s.play_count
    """)
    rows = cursor.fetchall()
    songs = []
    for r in rows:
        songs.append({
            'song_id': r.song_id, 'song_title': r.song_title,
            'song_language': r.song_language, 'album_title': r.album_title,
            'all_creators': r.all_creators, 'play_count': r.play_count or 0
        })
    conn.close()
    return render_template_string(BASE_TEMPLATE.replace('__CONTENT_BLOCK__', KTV_HTML), songs_json=json.dumps(songs), active_page='ktv')

@app.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit_song(id):
    conn = get_db_connection()
    cursor = conn.cursor()
    if request.method == 'POST':
        try:
            title = request.form['song_title']
            lang = request.form['song_language']
            al_new = request.form.get('al_new', '').strip()
            al_sel = request.form.get('al_sel')
            a_id = None
            if al_new:
                a_id = get_next_id(cursor, 'Albums', 'album_id')
                cursor.execute("INSERT INTO Albums (album_id, album_title, album_date) VALUES (?, ?, GETDATE())", (a_id, al_new))
            else: a_id = al_sel if al_sel else None

            cursor.execute("UPDATE Songs SET song_title=?, song_language=?, album_id=? WHERE song_id=?", (title, lang, a_id, id))
            cursor.execute("DELETE FROM Song_Creator_Roles WHERE song_id=?", (id,))
            roles = [('歌手','s_s','s_n'), ('作曲','c_s','c_n'), ('作詞','l_s','l_n')]
            for r_name, sel_k, new_k in roles:
                c_id = None
                new_n = request.form.get(new_k, '').strip()
                if new_n:
                    c_id = get_next_id(cursor, 'Creators', 'creator_id')
                    cursor.execute("INSERT INTO Creators (creator_id, creator_name) VALUES (?, ?)", (c_id, new_n))
                else: c_id = request.form.get(sel_k)
                if c_id: cursor.execute("INSERT INTO Song_Creator_Roles (song_id, creator_id, role) VALUES (?, ?, ?)", (id, c_id, r_name))
            conn.commit()
            flash(f'作品 #{id} 修改成功！', 'success')
            return redirect(url_for('index'))
        except Exception as e:
            conn.rollback(); flash(f'修改失敗: {str(e)}', 'danger')

    cursor.execute("SELECT * FROM Songs WHERE song_id=?", (id,))
    song = cursor.fetchone()
    cursor.execute("SELECT album_id, album_title FROM Albums"); als = cursor.fetchall()
    cursor.execute("SELECT creator_id, creator_name FROM Creators"); crs = cursor.fetchall()
    cursor.execute("SELECT role, creator_id FROM Song_Creator_Roles WHERE song_id=?", (id,))
    roles_rows = cursor.fetchall()
    current_roles = {'歌手': None, '作曲': None, '作詞': None}
    for r in roles_rows: current_roles[r.role] = r.creator_id
    conn.close()
    return render_template_string(BASE_TEMPLATE.replace('__CONTENT_BLOCK__', EDIT_SONG_HTML), song=song, albums=als, creators=crs, current_roles=current_roles, active_page='home')

@app.route('/ml')
def ml_analysis():
    conn = get_db_connection()
    cursor = conn.cursor()
    ml_sql = """
EXEC sp_execute_external_script @language = N'Python', @script = N'
import pandas as pd
from sklearn.cluster import KMeans
df = InputDataSet
features = df[["singer_ratio", "composer_ratio", "lyricist_ratio"]]
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
kmeans.fit(features)
df["cluster_id"] = kmeans.labels_
def get_p(c):
    if c == 0: return "純粹歌者"
    elif c == 1: return "幕後創作人"
    else: return "全能創作歌手"
df["marketing_persona"] = df["cluster_id"].apply(get_p)
OutputDataSet = df[["creator_name", "singer_ratio", "composer_ratio", "lyricist_ratio", "cluster_id", "marketing_persona"]]
', @input_data_1 = N'
SELECT c.creator_name, CAST(SUM(CASE WHEN scr.role = ''歌手'' THEN 1 ELSE 0 END) AS FLOAT) / COUNT(*) AS singer_ratio,
CAST(SUM(CASE WHEN scr.role = ''作曲'' THEN 1 ELSE 0 END) AS FLOAT) / COUNT(*) AS composer_ratio,
CAST(SUM(CASE WHEN scr.role = ''作詞'' THEN 1 ELSE 0 END) AS FLOAT) / COUNT(*) AS lyricist_ratio
FROM Song_Creator_Roles scr JOIN Creators c ON scr.creator_id = c.creator_id
GROUP BY c.creator_name HAVING COUNT(*) > 0'
WITH RESULT SETS ((creator_name NVARCHAR(255), singer_ratio FLOAT, composer_ratio FLOAT, lyricist_ratio FLOAT, cluster_id INT, marketing_persona NVARCHAR(100)));
"""
    try:
        cursor.execute(ml_sql); results = cursor.fetchall()
        counts = {'vocalist': 0, 'bts': 0, 'allround': 0}
        for r in results:
            if r.cluster_id == 0: counts['vocalist'] += 1
            elif r.cluster_id == 1: counts['bts'] += 1
            else: counts['allround'] += 1
    except Exception as e: flash(f"AI 分析失敗: {str(e)}", "danger"); results, counts = [], {'vocalist': 0, 'bts': 0, 'allround': 0}
    conn.close()
    return render_template_string(BASE_TEMPLATE.replace('__CONTENT_BLOCK__', ML_HTML), ml_results=results, persona_counts=counts, active_page='ml')

@app.route('/add', methods=['GET', 'POST'])
def add_song():
    conn = get_db_connection(); cursor = conn.cursor()
    if request.method == 'POST':
        try:
            title = request.form['song_title']; lang = request.form['song_language']
            al_new = request.form.get('al_new', '').strip(); al_sel = request.form.get('al_sel')
            a_id = None
            if al_new:
                a_id = get_next_id(cursor, 'Albums', 'album_id')
                cursor.execute("INSERT INTO Albums (album_id, album_title, album_date) VALUES (?, ?, GETDATE())", (a_id, al_new))
            else: a_id = al_sel if al_sel else None
            s_id = get_next_id(cursor, 'Songs', 'song_id')
            # 新增時 play_count 預設為 0
            cursor.execute("INSERT INTO Songs (song_id, song_title, song_language, album_id, play_count) VALUES (?, ?, ?, ?, 0)", (s_id, title, lang, a_id))
            roles = [('歌手','s_s','s_n'), ('作曲','c_s','c_n'), ('作詞','l_s','l_n')]
            for r_name, sel_k, new_k in roles:
                c_id = None; new_n = request.form.get(new_k, '').strip()
                if new_n:
                    c_id = get_next_id(cursor, 'Creators', 'creator_id')
                    cursor.execute("INSERT INTO Creators (creator_id, creator_name) VALUES (?, ?)", (c_id, new_n))
                else: c_id = request.form.get(sel_k)
                if c_id: cursor.execute("INSERT INTO Song_Creator_Roles (song_id, creator_id, role) VALUES (?, ?, ?)", (s_id, c_id, r_name))
            conn.commit(); flash(f'成功發行作品 #{s_id}', 'success')
            return redirect(url_for('index'))
        except Exception as e: conn.rollback(); flash(f'發行失敗: {str(e)}', 'danger')
    cursor.execute("SELECT album_id, album_title FROM Albums"); als = cursor.fetchall()
    cursor.execute("SELECT creator_id, creator_name FROM Creators"); crs = cursor.fetchall()
    conn.close()
    return render_template_string(BASE_TEMPLATE.replace('__CONTENT_BLOCK__', ADD_SONG_HTML_V2), albums=als, creators=crs, active_page='add')

ADD_SONG_HTML_V2 = """
<div class="row justify-content-center">
    <div class="col-lg-8 animate__animated animate__zoomIn">
        <form method="POST" class="card p-5 border-0 shadow-lg">
            <h4 class="fw-bold mb-4 text-primary"><i class="fas fa-file-signature me-2"></i>錄入新曲目發行</h4>
            <div class="mb-4"><label class="form-label fw-bold small text-subheader">作品名稱</label><input type="text" name="song_title" class="form-control form-control-lg" required></div>
            <div class="row mb-4">
                <div class="col-md-6"><label class="form-label fw-bold small text-subheader">語言</label><select name="song_language" class="form-select"><option value="國語">國語</option><option value="英語">英語</option><option value="粵語">粵語</option><option value="台語">台語</option><option value="其他">其他</option></select></div>
                <div class="col-md-6"><label class="form-label fw-bold small text-subheader">專輯/單曲設定</label>
                    <select name="al_sel" id="al_s" class="form-select mb-2"><option value="">-- 單曲 --</option>{% for a in albums %}<option value="{{ a.album_id }}">{{ a.album_title }}</option>{% endfor %}</select>
                    <input type="text" name="al_new" id="al_n" class="form-control" placeholder="或建立新專輯" oninput="toggleInput('al_s','al_n')">
                </div>
            </div>
            <div class="p-4 bg-light rounded-4 mb-4 border shadow-sm">
                <h6 class="fw-bold mb-3 border-bottom pb-2 text-dark">製作群詳情</h6>
                {% for r in [('歌手','s_s','s_n'),('作曲','c_s','c_n'),('作詞','l_s','l_n')] %}
                <div class="row g-2 mb-3 align-items-center">
                    <div class="col-3 text-end fw-bold small text-secondary">{{ r[0] }}:</div>
                    <div class="col-4"><select name="{{ r[1] }}" id="{{ r[1] }}" class="form-select form-select-sm"><option value="">-- 選擇 --</option>{% for c in creators %}<option value="{{ c.creator_id }}">{{ c.creator_name }}</option>{% endfor %}</select></div>
                    <div class="col-5"><input type="text" name="{{ r[2] }}" id="{{ r[2] }}" class="form-control form-control-sm" placeholder="或手動輸入姓名" oninput="toggleInput('{{ r[1] }}','{{ r[2] }}')"></div>
                </div>
                {% endfor %}
            </div>
            <button type="submit" class="btn btn-primary py-3 fw-bold rounded-pill shadow-lg">確認入庫並發行</button>
        </form>
    </div>
</div>
"""

@app.route('/delete/<int:id>')
def delete_song(id):
    conn = get_db_connection(); cursor = conn.cursor()
    try:
        cursor.execute("DELETE FROM Song_Creator_Roles WHERE song_id = ?", (id,))
        cursor.execute("DELETE FROM Songs WHERE song_id = ?", (id,))
        conn.commit(); flash('作品已成功撤回', 'warning')
    except Exception as e: conn.rollback(); flash(f'撤回失敗: {str(e)}', 'danger')
    conn.close(); return redirect(url_for('index'))

@app.route('/logs')
def logs():
    conn = get_db_connection(); cursor = conn.cursor()
    cursor.execute("SELECT * FROM Songs_Deleted_Log ORDER BY deleted_at DESC")
    data = cursor.fetchall(); conn.close()
    return render_template_string(BASE_TEMPLATE.replace('__CONTENT_BLOCK__', """
    <div class="card p-4 border-0 shadow-sm animate__animated animate__fadeIn">
        <h5 class="fw-bold mb-4 text-danger"><i class="fas fa-history me-2"></i>系統審計紀錄 (Audit Logs)</h5>
        <div class="table-responsive">
            <table class="table table-hover align-middle">
                <thead class="table-light"><tr><th>日誌 ID</th><th>受影響曲目</th><th>刪除時間</th><th>操作用戶</th></tr></thead>
                <tbody>{% for d in data %}<tr><td>#{{ d.log_id }}</td><td class="fw-bold">{{ d.song_title }}</td><td>{{ d.deleted_at.strftime('%Y-%m-%d %H:%M') }}</td><td><span class="badge bg-dark rounded-pill">{{ d.deleted_by }}</span></td></tr>{% endfor %}</tbody>
            </table>
        </div>
    </div>
    """), data=data, active_page='logs')

if __name__ == '__main__':
    app.run(debug=True)